# Site settings
title: Vilo Café
email: your-email@domain.com
url: "https://Vilocafe.github.io"
description: "Cafetería y Pastelería"
keywords: "Cafetería, Pastelería, cafe, San Telmo, Buenos Aires, Argentina, medialunas, postres, coffee, espresso"
skills: "Cafetería y Pastelería"
meta_author: Vilo Café

# Color settings
color:
  primary: "#67764f"
  primary-rgb: "103,118,79"
  secondary: "#67764f"
  secondary-dark: "#4a5238"

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag

# Social networks usernames (uncomment to use)
# social:
#   - title: github
#     url: http://github.com/jekyll
#   - title: whatsapp
#     url: https://wa.me/541136773931

# Postal address (add as many lines as necessary)
address:
  - line: Avenida Independencia 624
  - line: San Telmo, Argentina
